rescue fw image and POST revamping

diff --git a/openwrt/common/sbin/logrotate b/openwrt/common/sbin/logrotate
--- a/openwrt/common/sbin/logrotate
+++ b/openwrt/common/sbin/logrotate
@@ -3,32 +3,37 @@
 ## Simple logrotate script
 ## http://superglue.it | Danja Vasiliev, 2014
 ##
-## Takes filepath(s) as argument:
-## logrotate /www/access.log [/www/error.log] [/www/admin/admin.log]
+## Takes filepath or file mask as argument:
+##   logrotate /www/access.log [/www/error*.log]
+## and gzip compresses them inplace
 
-## default settings, redefine in config file mentioned below 
-ROTATE=30  ## backlogs to keep
-DATE=$(date +%d.%m.%y-%H:%M:%S)
-LOGS=( $* )
+## default settings
+## override in config file mentioned below 
 
-## source config
-CONF='/etc/logrotate.conf'
-[[ -e $CONF ]] && . $CONF
+_ROTATE=30  ## backlogs to keep, days
+_DATE=$(date +%d.%m.%y-%H:%M:%S)
+_LOGS=( $* )
+
+## read config file 
+_CONF='/etc/logrotate.conf'
+[[ -e $_CONF ]] && . $_CONF
 
 function err {
-  printf %s": "%s"\n" "$(basename $0)" "$1"; exit 1
+  local _ERR=$?
+  printf %s": "%s"\n" "$(basename $0)" "$1"
+  exit $_ERR
 }
 
-[[ -z $LOGS ]] && err 'missing input file'
-[[ ! -e $LOGS ]] && err 'input file not readable'
+[[ -n $_LOGS ]] || err 'missing input file'
+[[ -e $_LOGS ]] || err 'input file not readable'
 
-for FILE in ${LOGS[@]}; do
+for _FILE in ${_LOGS[@]}; do
   ## get number of backlogs and purge unwanted
-  N=( $(ls -1 -r $FILE*.gz &>/dev/null || echo '') ) 
-  [[ ${#N[@]} -gt $((ROTATE-1)) ]] && rm -f ${N[@]:$((ROTATE-1)) }
+  _NUM=( $(ls -1 -r $_FILE*.gz &>/dev/null || echo '') ) 
+  [[ ${#_NUM[@]} -gt $((_ROTATE-1)) ]] && rm -f ${_NUM[@]:$((_ROTATE-1)) }
   ## compress and move
-  gzip -f $FILE || err 'failed to gzip file'
-  mv $FILE.gz "$FILE""$DATE".gz || err 'failed to rename archive'
+  gzip -f $_FILE || err 'failed to gzip file'
+  mv $_FILE.gz "$_FILE"-"$_DATE".gz || err 'failed to rename archive'
 done
 
-exit 0
+exit $?
